<div class="PaddedContents">

    <br/>
    <h2 class="CenterMe">JavaScript notes - Async</h2>       
    <h4 class="CenterMe">You can type the JavaScript code  
      <a class="CenterMe" href="https://replit.com/languages/nodejs" target="_new">on replit.com</a> 
      to see how it works (it is nodejs but you can also choose JavaScript): <br/>   
    </h4>
  
    <br/>
  
    <div style="position:fixed; left:12px; top: 10vh; width:8vw; ">
      <p>
        <a  href="/javascript-notes-async/#promises">Promises</a>
      <p>        
        <a  href="/javascript-notes-async/#catch">Catch-Finally</a>      
      </p>       
      <p>        
        <a  href="/javascript-notes-async/#chains">Chains</a>      
      </p>  
      <p>
        <a  href="/javascript-notes-async/#static">Static func.</a>
      </p>
      <p>
        <a  href="/javascript-notes-async/#await">Await</a>
      </p>
    </div>
    
    <div class="PaddedContents">
  
      <!-------------------------------------------------------------->
      <!--Promises-->
      <!-------------------------------------------------------------->
      <div id="promises"></div><br/>
      <hr class="hrHeaderClass" />
          <h2 class="CenterMe">Promises</h2>
      <hr class="hrHeaderClass"/>
  
      <code><strong><u>Basics</u></strong></code><br />
      Promises are objects.<br/>
      The promise object returns properties: <b>state</b> (pending, fulfilled, rejected), <b>result</b> (undefined, value, error).<br/>
      A promise that is fulfilled or rejected is settled.<br/>

      <div class="codeBlock">
        let myPromise = new Promise ( function(resolve, reject)<br/>
        &lbrace;<br/>
          console.log("About to call func with setTimeOut");<br/>
          setTimeout(<br/>
            &nbsp;() => &lbrace;<br/>
            &nbsp;&nbsp;console.log("Sending a resolve");<br/>
            &nbsp;&nbsp;resolve("RESOLVED!!!");<br/>
            &rbrace;, 3000)<br/>
          console.log("Waiting for setTimeout to finish...");  <br/>
        &rbrace;);<br/><br/>
        
        let consumePromise = () => &lbrace;<br/>
        &nbsp; myPromise.then( <br/>
        &nbsp;&nbsp;(resolve) => console.log(resolve) );<br/>
        &rbrace;<br/><br/>
        
        consumePromise();<br/>
      </div>


  
    <img width="100%" src="assets\images\js\promise1.png" alt="promise 1" /><br/><br/>

      The above example only has code for the resolve, if we wanted to have somewhere in the code to send the reject, it would look something like <br/>
      <div class="codeBlock">
          reject( new Error("Rejected!!!"));
      </div>    
      and then in the code inside the then() you do 
      <div class="codeBlock">
        myPromise.then( <br/>
        (resolve) => console.log(resolve) ;<br/>
        (reject) => console.log(reject) )<br/>
    </div>
    We could also do this.  Notice if the promise doesn't return a resolve, just use null in its place, don't just ignore it and leave it out.<br/>
    <div class="codeBlock">
        let myPromise = new Promise ( function(resolve, reject)<br/>
        &lbrace;<br/>
            &nbsp;console.log("About to call func with setTimeOut");<br/>
            &nbsp;setTimeout(<br/>
                &nbsp;() => &lbrace;<br/>
                    &nbsp;&nbsp;   console.log("Sending a reject");<br/>
                    &nbsp;&nbsp; reject(new Error("REJECTED!!!"));<br/>
                    &nbsp;&rbrace;, 3000)<br/>
                    &nbsp;console.log("Waiting for setTimeout to finish...");  <br/>
        &rbrace;);<br/><br/>

        let consumePromise = () => &lbrace;<br/>
            &nbsp; myPromise.then( <br/>
                &nbsp;&nbsp;  (null),<br/>
                &nbsp;&nbsp; (reject) => console.log(reject));<br/>
        &rbrace;
        <br/><br/>
        consumePromise();<br/>
    </div><br/>
    <img width="100%" src="assets\images\js\promise2.png" alt="promise 2" /><br/><br/>
    The consumePromise doesn't have to name (resolve) and (reject) that way, you can name it whatever. Changing that part of the code to this also works:
    <div class="codeBlock">
        let consumePromise = () => &lbrace;<br/>
        &nbsp; myPromise.then( <br/>
        &nbsp; &nbsp; (null),<br/>
        &nbsp; &nbsp; (rejectOHNO) => console.log(rejectOHNO));<br/>
          &rbrace;<br/>
    </div><br/>
    If instead of reject(new Error("REJECTED!!!") we do reject("REJECTED!!!"); it will still go to the reject but it won't display as an error, but as a string.<br/>

    <!-------------------------------------------------------------->
    <!--catch finally-->
    <!-------------------------------------------------------------->
    <div id="catch"></div><br/>
    <hr class="hrHeaderClass" />
        <h2 class="CenterMe">Catch-Finally</h2>
    <hr class="hrHeaderClass"/>

    <code><strong><u>catch</u></strong></code><br />

    We could also be catching an error this way:<br/>
    <div class="codeBlock">
        let consumePromise = () => &lbrace;<br/>
           &nbsp; myPromise.catch(<br/>
           &nbsp;&nbsp;(errorOHNO) => &lbrace;console.log(errorOHNO);&rbrace;<br/>
           &nbsp;)<br/>
          &rbrace;<br/>
    </div>
    <br/>
    The catch will happen even if we don't send an Error, so having only reject( "REJECTED OH NO!"); will still go to the catch block.<br/>
    If we have both the reject and the catch, the catch will not happen:<br/>
    <div class="codeBlock">
        let consumePromise = () => &lbrace;<br/>
        &nbsp;myPromise.then(<br/>
        &nbsp; &nbsp; (resolve) => console.log("hello"),<br/>
        &nbsp; &nbsp; (reject) => console.log("OH no!!" + reject)<br/>
        &nbsp;  ).catch(<br/>
        &nbsp; &nbsp;    (errorOHNO) => &lbrace;console.log("IN CATCH");&rbrace;<br/>
        &nbsp;  )<br/>
          &rbrace;<br/>
    </div>
    <br/>
    <img width="100%" src="assets\images\js\promise3.png" alt="promise 3" /><br/><br/>

    <code><strong><u>finally</u></strong></code><br />
    Finally always happen, no matter resolve or reject.<br/>
    <div class="codeBlock">
        let consumePromise = () => &lbrace;<br/>
        &nbsp; myPromise.then(<br/>
        &nbsp; &nbsp;  (resolve) => console.log("hello"),<br/>
        &nbsp; &nbsp;  (reject) => console.log("OH no!!" + reject)<br/>
        &nbsp; ).catch(<br/>
        &nbsp; &nbsp;    (errorOHNO) => &lbrace;console.log("IN CATCH");&rbrace;<br/>
        &nbsp;  ).finally(<br/>
        &nbsp; &nbsp;     console.log("FINALLY!")<br/>
        &nbsp;   )<br/>                    
    </div>
    But look what that prints:
    <div class="codeBlock">
        About to call func with setTimeOut<br/>
        Waiting for setTimeout to finish...<br/>
        <b>FINALLY!</b><br/>
        Hint: hit control+c anytime to enter REPL.<br/>
        Sending a reject<br/>
        OH no!!Error: rejected!!!<br/>
    </div>  


     <!-------------------------------------------------------------->
    <!--chains-->
    <!-------------------------------------------------------------->
    <div id="chains"></div><br/>
    <hr class="hrHeaderClass" />
        <h2 class="CenterMe">Chains</h2>
    <hr class="hrHeaderClass"/>





    </div>    



    


</div>
    