<div class="PaddedContents ">
  
    
  
    <div class="leftLinks" #HeadingsContainer>      
      <left-links ></left-links>      
    </div>      
    
    <div class="PaddedContents PaddedContentsTopics">
      <h4 class="CenterMe">You can type the JavaScript code  
        <a class="CenterMe" href="https://replit.com/languages/nodejs" target="_new">on replit.com</a> 
        to see how it works (it is nodejs but you can also choose JavaScript): <br/>   
      </h4>

      <p class="HeadingSubTopic" id="General">General</p>
      We need this when we have a few operations to do, that take some time, and can be done independently, or when we need the operation to access some 
      external service, like an http call would be.<br/>
      One way to do this is like this, though it can get messy quickly:
      <pre>
        <code>
          function doStep1(init, <b>callback</b>) &lbrace;
            const result = init + 1;
            callback(result);
          &rbrace;
          
          function doStep2(init, callback)  &lbrace;
            const result = init + 2;
            callback(result);
            &rbrace;
          
          function doOperation() &lbrace;
            doStep1(0, (result1) =>  &lbrace;
              
              console.log(result1); //1
              
              doStep2(result1, (result2) =>  &lbrace;
                console.log(result2);      
                &rbrace;)
              
                &rbrace;);    
                &rbrace;;
          
          doOperation();
          
        </code>
      </pre>

      <img width="100%" src="assets\images\js\pass_callback_for_async.png" alt="callback for async" /><br/><br/>
      <!-------------------------------------------------------------->
      <!--Promises-->
      <!-------------------------------------------------------------->     
      
      <p class="HeadingSubTopic" id="promises">Promises</p>
      <p class="HeadingSubTopic2" id="promises">Basic</p>
      A promise is an object returned by an asynchronous function, which represents the current state of the operation<br/>
      Promises are objects.  At the time the promise is returned to the caller, the operation often isn't finished, 
      but the promise object provides methods to handle the eventual success or failure of the operation.<br/>
      The promise object returns properties: <b>state</b> (pending, fulfilled, rejected), <b>result</b> (undefined, value, error).<br/>
      A promise that is fulfilled or rejected is settled.<br/>

      One example of this could be a fetch operation.
      <br/>
      <pre>
        <code>
          const fetchPromise = fetch('https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml');

          //call the fetchPromise and when it's done (then), get the text, which is also async, so we need another then.
          //it would be similar if the fetch returned json instead of xml, you would use .json() instead of .text().
          fetchPromise
            .then((response) =&gt; &lbrace;
              if (!response.ok) &lbrace;
                throw new Error(`HTTP error: $&lbrace;response.status&rbrace;`);
            &rbrace;
              return response.text();
            &rbrace;)
            .then((data) =&gt; &lbrace;
              console.log("hey"); console.log(data);
            &rbrace;);
        </code>        
      </pre>
      Or we can also do our own promises.
      <pre>
        <code>
          let myPromise = new Promise ( function(resolve, reject)
          &lbrace;
            console.log("About to call func with setTimeOut");
            setTimeout(
              &nbsp;() => &lbrace;
              &nbsp;&nbsp;console.log("Sending a resolve");
              &nbsp;&nbsp;resolve("RESOLVED!!!");
              &rbrace;, 3000)
            console.log("Waiting for setTimeout to finish...");  
          &rbrace;);<br/>
          
          let consumePromise = () => &lbrace;
          &nbsp; myPromise.then( 
          &nbsp;&nbsp;(resolve) => console.log(resolve) );
          &rbrace;<br/>
          
          consumePromise();
        </code>
      </pre>
 


  
    <img width="100%" src="assets\images\js\promise1.png" alt="promise 1" /><br/><br/>

      The above example only has code for the resolve, if we wanted to have somewhere in the code to send the reject, it would look something like <br/>      
        <pre>
          <code>
            reject( new Error("Rejected!!!"));  
          </code>
        </pre>          
      
      and then in the code inside the then() you do 

        <pre>
          <code>
            myPromise.then( 
            (resolve) => console.log(resolve) ;
            (reject) => console.log(reject) )
          </code>
        </pre>
            
    We could also do this.  Notice if the promise doesn't return a resolve, just use null in its place, don't just ignore it and leave it out.<br/>
    
      <pre>
        <code>
          let myPromise = new Promise ( function(resolve, reject)
          &lbrace;
              &nbsp;console.log("About to call func with setTimeOut");
              &nbsp;setTimeout(
                  &nbsp;() => &lbrace;
                      &nbsp;&nbsp;   console.log("Sending a reject");
                      &nbsp;&nbsp; reject(new Error("REJECTED!!!"));
                      &nbsp;&rbrace;, 3000)
                      &nbsp;console.log("Waiting for setTimeout to finish...");  
          &rbrace;);<br/>
  
          let consumePromise = () => &lbrace;
              &nbsp; myPromise.then( 
                  &nbsp;&nbsp;  (null),
                  &nbsp;&nbsp; (reject) => console.log(reject));
          &rbrace;
          <br/>
          consumePromise();
        </code>
      </pre>
       
    <br/>
    <img width="100%" src="assets\images\js\promise2.png" alt="promise 2" /><br/><br/>
    <!--
    The consumePromise doesn't have to name (resolve) and (reject) that way, you can name it whatever. Changing that part of the code to this also works:
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp; myPromise.then( 
        &nbsp; &nbsp; (null),
        &nbsp; &nbsp; (rejectOHNO) => console.log(rejectOHNO));
          &rbrace;
      </code>
    </pre>
    -->
    <br/>
    If instead of reject(new Error("REJECTED!!!") we do reject("REJECTED!!!"); it will still go to the reject but it won't display as an error, but as a string.<br/>

    <!-------------------------------------------------------------->
    <!--catch finally-->
    <!-------------------------------------------------------------->   
    
    <p class="HeadingSubTopic" id="catch">Try-Catch</p>
    <p class="HeadingSubTopic2">catch</p>

    We could also be catching an error this way:<br/>
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp; myPromise.catch(
        &nbsp;&nbsp;(error) => &lbrace;console.log(error);&rbrace;
        &nbsp;)
       &rbrace;
      </code>
    </pre>
    
    <br/>
    The catch will happen even if we don't send an Error, so having only reject( "REJECTED OH NO!"); will still go to the catch block.<br/>
    If we have both the reject and the catch, the catch will not happen:<br/>
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp;myPromise.then(
        &nbsp; &nbsp; (resolve) => console.log("hello"),
        &nbsp; &nbsp; (reject) => console.log("OH no!!" + reject)
        &nbsp;  ).catch(
        &nbsp; &nbsp;    (errorOHNO) => &lbrace;console.log("IN CATCH");&rbrace;
        &nbsp;  )
          &rbrace;
      </code>
    </pre>
    
    <br/>
    <img width="100%" src="assets\images\js\promise3.png" alt="promise 3" /><br/><br/>

    
    <p class="HeadingSubTopic2">finally</p>
    Finally always happen, no matter resolve or reject.<br/>
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp; myPromise.then(
        &nbsp; &nbsp;  (resolve) => console.log("hello"),
        &nbsp; &nbsp;  (reject) => console.log("OH no!!" + reject)
        &nbsp; ).catch(
        &nbsp; &nbsp;    (errorOHNO) => &lbrace;console.log("IN CATCH");&rbrace;
        &nbsp;  ).finally(
        &nbsp; &nbsp;     console.log("FINALLY!")
        &nbsp;   )
      </code>
    </pre>
    
    But look what that prints:
    <pre>
      <samp>
        About to call func with setTimeOut
        Waiting for setTimeout to finish...
        <b>FINALLY!</b>
        Hint: hit control+c anytime to enter REPL.
        Sending a reject
        OH no!!Error: rejected!!!
      </samp>
    </pre>
    


    <!-------------------------------------------------------------->
    <!--chains-->
    <!-------------------------------------------------------------->
    <p class="HeadingSubTopic" id="chains">Chains</p>

    
    We can have then after then, such as then(...).then(...) etc. However, the resolve from the myPromise will only make it to the first then.
    If than then doesn't return it, the following thens will not have it:

    <img width="100%" src="assets\images\js\promisechain.png" alt="promise chain" /><br/><br/>
    <br/>
    But if the previous then returns, then:<br/>
    <img width="100%" src="assets\images\js\promisechain2.png" alt="promise chain 2" /><br/><br/>

    If we had more than one promise (let myPromise = new Promise), the then() can return one of the additional promises instead of just returning a string or whatever.<br/>




    <!-------------------------------------------------------------->
    <!--static functions-->
    <!-------------------------------------------------------------->  

    <p class="HeadingSubTopic" id="static">Static functions</p>
    JS has some static functions to deal with promises. This is just a brief summary.<br/>

    
    <p class="HeadingSubTopic2">all</p>

    <pre>
      <code>
        Promise.all([myPromise1, myPromise2]).then(
        (values) => console.log("ALL DONE with " + values)
      )
      </code>
    </pre>
    <br/>

    <img width="100%" src="assets\images\js\promise_all.png" alt="promise all" /><br/><br/>
    It is a good idea to have a catch with the Promise.all in case one of the promises fails.<br/>

    <p class="HeadingSubTopic2">allsettled</p>
    This will have the then happen, regardless of resolve or reject.  And values will have the status and result of the promises.

    
    <p class="HeadingSubTopic2">any</p>

    Promise.any[ list of promises] will wait for just one to finish.  Once that happens, the others are ignored.<br/>

    
    <p class="HeadingSubTopic2">race</p>

    Will happen with whatever promise finishes first, it doesn't matter if with resolve or reject.<br/>

    
    <p class="HeadingSubTopic2">resolve</p>
    the resolve will call the first function in the arguments.
    <pre>
      <code>
        Promise.resolve("YAY").then(
        &nbsp;   ()=>console.log("pretend I'm a func called 4 resolve"),
        &nbsp;   ()=>console.log("pretend I'm a func called 4 reject")
         )
      </code>
    </pre>
    <br/>

    <img width="100%" src="assets\images\js\resolve.png" alt="resolve" /><br/><br/>


    
    <p class="HeadingSubTopic2">reject</p>
    similar to the resolve but it goes to the second function provided, the reject one.<br/>
    <pre>
      <code>
        Promise.reject( new Error("Oops")).then(
        &nbsp;  ()=>console.log("pretend I'm a func called 4 resolve"),
        &nbsp;  ()=>console.log("pretend I'm a func called 4 reject")
        )
      </code>
    </pre>
    


    <!-------------------------------------------------------------->
    <!--Await-->
    <!-------------------------------------------------------------->

    <p class="HeadingSubTopic" id="await">Await</p>
    
    AWAIT is used to wait for a promise or a value if what we return is not a promise, but it will be turned into a promise.  
    <b>AWAIT has to be called inside a async function.</b><br/>
    If the Promise bein awaited is rejected, the await expression throws the rejected value.<br/>
    <b>The await will wait for the promise it got to be resolved.</b>  If we return a value right away, it will not be waiting.  If the called
    function waits and then returns something, the await will have moved on.  It expects a promise, then it waits for it to finish.  It doesn't wait 
    for the promise to be returned after a while.
    <br/>
    The fetch example that we had before with promises, would look like:
    <pre>
      <code>

        async function fetchData()&lbrace;
          try&lbrace;
            const response = await fetch('https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml');
            if (!response.ok) &lbrace;
                throw new Error(`HTTP error: $&lbrace;response.status&rbrace;`);
            &rbrace;
            const theData = await response.text();

            console.log(theData);
            &rbrace;
          catch&lbrace;
            console.log("oops");
            &rbrace;
        &rbrace;

        fetchData();
      </code>
    </pre>
    Async functions always returns a promise, so if you want the function to return theData or whatever, you need to get it this way:
    <pre>
      <code>
        const promise = fetchData();
        promise.then((data) => console.log(data));
      </code>
    </pre>
    <pre>
      <code>
        function callMe()&lbrace;
        &nbsp; console.log("returning promise with timeout");
        &nbsp; return new Promise(function (resolve,reject) &lbrace;
        &nbsp;&nbsp;   setTimeout(() => &lbrace;
        &nbsp;&nbsp;     resolve(9);
        &nbsp;   &rbrace;, 3000);
        &nbsp;  &rbrace;);
       &rbrace;<br/>
       
       async function iCallWait()&lbrace;
       &nbsp;   let vble = await callMe()  ;  
       &nbsp;   console.log("Hello, I got " + vble);
       &nbsp;  &rbrace;<br/>
       
       iCallWait();
      </code>
    </pre>
    <br/>
    <img width="100%" src="assets\images\js\await1.png" alt="await 1" /><br/><br/>

    If the promise can reject, do a try-catch:<br/>

    <pre>
      <code>
        async function iCallWait()&lbrace;
        &nbsp; try&lbrace;
        &nbsp; &nbsp;  let vble = await callMe()  ;  
        &nbsp; &nbsp;  console.log("Hello, I got " + vble);
        &nbsp; &nbsp;   &rbrace;catch&lbrace;
        &nbsp;     console.log("oh no");
            &rbrace;  
      </code>
    </pre>
    <br/>
    Could also do this but less clear: <span class="notesStrong">var response = await callMe().catch((err) => &lbrace; console.error(err); &rbrace;);</span>><br/><br/>
    You can also do: <span class="notesStrong">let response = await fetch(url); </span> (in async function, try in browser's console, Calling fetch () returns a promise)<br/><br/>
    If we call a function with await that just waits and then returns something, the wait will not wait (see explanation at top of section):<br/><br/>
    <pre>
      <code>
        function callMe()&lbrace;
        &nbsp;setTimeout(() => &lbrace;
        &nbsp;&nbsp;  return 9;
        &nbsp;  &rbrace;, 3000);  
        &rbrace;
      </code>
    </pre>
    


    <p class="HeadingSubTopic" id="workers">Workers</p>

    Workers give you the ability to start a task in a different thread.  But workers cannot be accessing the same variables, for example something 
    on the window or the DOM.  (can't really lock them like in C#).  Communication happens via sending messages.  <br/>
    Create the worker this way: <b>const worker = new Worker('./somefilewhereourcodeis.js'); </b><br/>
    When we are ready to call the worker to do its job: <b>worker.postMessage(&lbrace; command: 'generateorwhatever', someparam, &rbrace;);</b><br/>
    If we need to know when the worker is done, and possible get data back we need to <b>worker.addEventListener('message', (message) => &lbrace;
      // do something with the message
    &rbrace;);</b><br/>
    In the code in the somefilewhereourcodeis.js. 
    <pre>
      <code>
        //listen to messages (calls) from the main thread.
        addEventListener("message", (message) => &lbrace;
          if (message.data.command === 'generateorwhatever') &lbrace;
            callSomeFunction(message.data.someparam);
          &rbrace;
        &rbrace;)

        //and in the function we are calling, to send the message back to the main thread.
        postMessage(whatever);
      </code>
    </pre>






    </div>    
</div>
    