<div class="PaddedContents">

    <br/>
    <h2 class="CenterMe">JavaScript notes - Async</h2>       
    <h4 class="CenterMe">You can type the JavaScript code  
      <a class="CenterMe" href="https://replit.com/languages/nodejs" target="_new">on replit.com</a> 
      to see how it works (it is nodejs but you can also choose JavaScript): <br/>   
    </h4>
  
    <br/>
  
    <div style="position:fixed; left:12px; top: 10vh; width:8vw; ">
      <p>
        <a  href="/javascript-notes-async/#promises">Promises</a>
      <p>        
        <a  href="/javascript-notes-async/#catch">Catch-Finally</a>      
      </p>       
      <p>        
        <a  href="/javascript-notes-async/#chains">Chains</a>      
      </p>  
      <p>
        <a  href="/javascript-notes-async/#static">Static func.</a>
      </p>
      <p>
        <a  href="/javascript-notes-async/#await">Await</a>
      </p>
    </div>
    
    <div class="PaddedContents">
  
      <!-------------------------------------------------------------->
      <!--Promises-->
      <!-------------------------------------------------------------->
      <div id="promises"></div><br/>
      <hr class="hrHeaderClass" />
          <h2 class="CenterMe">Promises</h2>
      <hr class="hrHeaderClass"/>
      
      <p class="HeadingSubTopic">Basics</p>
      Promises are objects.<br/>
      The promise object returns properties: <b>state</b> (pending, fulfilled, rejected), <b>result</b> (undefined, value, error).<br/>
      A promise that is fulfilled or rejected is settled.<br/>

      <pre>
        <code>
          let myPromise = new Promise ( function(resolve, reject)<
          &lbrace;
            console.log("About to call func with setTimeOut");
            setTimeout(
              &nbsp;() => &lbrace;
              &nbsp;&nbsp;console.log("Sending a resolve");
              &nbsp;&nbsp;resolve("RESOLVED!!!");
              &rbrace;, 3000)
            console.log("Waiting for setTimeout to finish...");  
          &rbrace;);<br/>
          
          let consumePromise = () => &lbrace;
          &nbsp; myPromise.then( 
          &nbsp;&nbsp;(resolve) => console.log(resolve) );
          &rbrace;<br/>
          
          consumePromise();
        </code>
      </pre>
 


  
    <img width="100%" src="assets\images\js\promise1.png" alt="promise 1" /><br/><br/>

      The above example only has code for the resolve, if we wanted to have somewhere in the code to send the reject, it would look something like <br/>      
        <pre>
          <code>
            reject( new Error("Rejected!!!"));  
          </code>
        </pre>          
      
      and then in the code inside the then() you do 

        <pre>
          <code>
            myPromise.then( 
            (resolve) => console.log(resolve) ;
            (reject) => console.log(reject) )
          </code>
        </pre>
            
    We could also do this.  Notice if the promise doesn't return a resolve, just use null in its place, don't just ignore it and leave it out.<br/>
    
      <pre>
        <code>
          let myPromise = new Promise ( function(resolve, reject)
          &lbrace
              &nbsp;console.log("About to call func with setTimeOut");
              &nbsp;setTimeout(
                  &nbsp;() => &lbrace;
                      &nbsp;&nbsp;   console.log("Sending a reject");
                      &nbsp;&nbsp; reject(new Error("REJECTED!!!"));
                      &nbsp;&rbrace;, 3000)
                      &nbsp;console.log("Waiting for setTimeout to finish...");  
          &rbrace;);<br/>
  
          let consumePromise = () => &lbrace;
              &nbsp; myPromise.then( 
                  &nbsp;&nbsp;  (null),
                  &nbsp;&nbsp; (reject) => console.log(reject));
          &rbrace;
          <br/>
          consumePromise();
        </code>
      </pre>
       
    <br/>
    <img width="100%" src="assets\images\js\promise2.png" alt="promise 2" /><br/><br/>
    The consumePromise doesn't have to name (resolve) and (reject) that way, you can name it whatever. Changing that part of the code to this also works:
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp; myPromise.then( 
        &nbsp; &nbsp; (null),
        &nbsp; &nbsp; (rejectOHNO) => console.log(rejectOHNO));
          &rbrace;
      </code>
    </pre>
    <br/>
    If instead of reject(new Error("REJECTED!!!") we do reject("REJECTED!!!"); it will still go to the reject but it won't display as an error, but as a string.<br/>

    <!-------------------------------------------------------------->
    <!--catch finally-->
    <!-------------------------------------------------------------->
    <div id="catch"></div><br/>
    <hr class="hrHeaderClass" />
        <h2 class="CenterMe">Catch-Finally</h2>
    <hr class="hrHeaderClass"/>

    
    <p class="HeadingSubTopic">catch</p>

    We could also be catching an error this way:<br/>
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp; myPromise.catch(
        &nbsp;&nbsp;(errorOHNO) => &lbrace;console.log(errorOHNO);&rbrace;
        &nbsp;)
       &rbrace;
      </code>
    </pre>
    
    <br/>
    The catch will happen even if we don't send an Error, so having only reject( "REJECTED OH NO!"); will still go to the catch block.<br/>
    If we have both the reject and the catch, the catch will not happen:<br/>
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp;myPromise.then(
        &nbsp; &nbsp; (resolve) => console.log("hello"),
        &nbsp; &nbsp; (reject) => console.log("OH no!!" + reject)
        &nbsp;  ).catch(
        &nbsp; &nbsp;    (errorOHNO) => &lbrace;console.log("IN CATCH");&rbrace;
        &nbsp;  )
          &rbrace;
      </code>
    </pre>
    
    <br/>
    <img width="100%" src="assets\images\js\promise3.png" alt="promise 3" /><br/><br/>

    
    <p class="HeadingSubTopic">finally</p>
    Finally always happen, no matter resolve or reject.<br/>
    <pre>
      <code>
        let consumePromise = () => &lbrace;
        &nbsp; myPromise.then(
        &nbsp; &nbsp;  (resolve) => console.log("hello"),
        &nbsp; &nbsp;  (reject) => console.log("OH no!!" + reject)
        &nbsp; ).catch(
        &nbsp; &nbsp;    (errorOHNO) => &lbrace;console.log("IN CATCH");&rbrace;
        &nbsp;  ).finally(
        &nbsp; &nbsp;     console.log("FINALLY!")
        &nbsp;   )
      </code>
    </pre>
    
    But look what that prints:
    <pre>
      <samp>
        About to call func with setTimeOut
        Waiting for setTimeout to finish...
        <b>FINALLY!</b>
        Hint: hit control+c anytime to enter REPL.
        Sending a reject
        OH no!!Error: rejected!!!
      </samp>
    </pre>
    


    <!-------------------------------------------------------------->
    <!--chains-->
    <!-------------------------------------------------------------->
    <div id="chains"></div><br/>
    <hr class="hrHeaderClass" />
        <h2 class="CenterMe">Chains</h2>
    <hr class="hrHeaderClass"/>

    We can have then after then, such as then(...).then(...) etc. However, the resolve from the myPromise will only make it to the first then.
    If than then doesn't return it, the following thens will not have it:

    <img width="100%" src="assets\images\js\promisechain.png" alt="promise chain" /><br/><br/>
    <br/>
    But if the previous then returns, then:<br/>
    <img width="100%" src="assets\images\js\promisechain2.png" alt="promise chain 2" /><br/><br/>

    If we had more than one promise (let myPromise = new Promise), the then() can return one of the additional promises instead of just returning a string or whatever.<br/>




    <!-------------------------------------------------------------->
    <!--static functions-->
    <!-------------------------------------------------------------->
    <div id="static"></div><br/>
    <hr class="hrHeaderClass" />
        <h2 class="CenterMe">Static functions</h2>
    <hr class="hrHeaderClass"/>

    JS has some static functions to deal with promises. This is just a brief summary.<br/>

    
    <p class="HeadingSubTopic">all</p>

    <pre>
      <code>
        Promise.all([myPromise1, myPromise2]).then(
        (values) => console.log("ALL DONE with " + values)
      )
      </code>
    </pre>
    <br/>

    <img width="100%" src="assets\images\js\promise_all.png" alt="promise all" /><br/><br/>
    It is a good idea to have a catch with the Promise.all in case one of the promises fails.<br/>

    <p class="HeadingSubTopic">allsettled</p>
    This will have the then happen, regardless of resolve or reject.  And values will have the status and result of the promises.

    
    <p class="HeadingSubTopic">any</p>

    Promise.any[ list of promises] will wait for just one to finish.  Once that happens, the others are ignored.<br/>

    
    <p class="HeadingSubTopic">race</p>

    Will happen with whatever promise finishes first, it doesn't matter if with resolve or reject.<br/>

    
    <p class="HeadingSubTopic">resolve</p>
    the resolve will call the first function in the arguments.
    <pre>
      <code>
        Promise.resolve("YAY").then(
        &nbsp;   ()=>console.log("pretend I'm a func called 4 resolve"),
        &nbsp;   ()=>console.log("pretend I'm a func called 4 reject")
         )
      </code>
    </pre>
    <br/>

    <img width="100%" src="assets\images\js\resolve.png" alt="resolve" /><br/><br/>


    
    <p class="HeadingSubTopic">reject</p>
    similar to the resolve but it goes to the second function provided, the reject one.<br/>
    <pre>
      <code>
        Promise.reject( new Error("Oops")).then(
        &nbsp;  ()=>console.log("pretend I'm a func called 4 resolve"),
        &nbsp;  ()=>console.log("pretend I'm a func called 4 reject")
        )
      </code>
    </pre>
    


    <!-------------------------------------------------------------->
    <!--Await-->
    <!-------------------------------------------------------------->
    <div id="await"></div><br/>
    <hr class="hrHeaderClass" />
        <h2 class="CenterMe">Await</h2>
    <hr class="hrHeaderClass"/>

    AWAIT is used to wait for a promise or a value if what we return is not a promise, but it will be turned into a promise.  
    <b>AWAIT has to be called inside a async function.</b><br/>
    If the Promise bein awaited is rejected, the await expression throws the rejected value.<br/>
    <b>The await will wait for the promise it got to be resolved.</b>  If we return a value right away, it will not be waiting.  If the called
    function waits and then returns something, the await will have moved on.  It expects a promise, then it waits for it to finish.  It doesn't wait 
    for the promise to be returned after a while.

    <pre>
      <code>
        function callMe()&lbrace;
        &nbsp; console.log("returning promise with timeout");
        &nbsp; return new Promise(function (resolve,reject) &lbrace;
        &nbsp;&nbsp;   setTimeout(() => &lbrace;
        &nbsp;&nbsp;     resolve(9);
        &nbsp;   &rbrace;, 3000);
        &nbsp;  &rbrace;);
       &rbrace;<br/>
       
       async function iCallWait()&lbrace;
       &nbsp;   let vble = await callMe()  ;  
       &nbsp;   console.log("Hello, I got " + vble);
       &nbsp;  &rbrace;<br/>
       
       iCallWait();
      </code>
    </pre>
    <br/>
    <img width="100%" src="assets\images\js\await1.png" alt="await 1" /><br/><br/>

    If the promise can reject, do a try-catch:<br/>

    <pre>
      <code>
        async function iCallWait()&lbrace;
        &nbsp; try&lbrace;
        &nbsp; &nbsp;  let vble = await callMe()  ;  
        &nbsp; &nbsp;  console.log("Hello, I got " + vble);
        &nbsp; &nbsp;   &rbrace;catch&lbrace;
        &nbsp;     console.log("oh no");
            &rbrace;  
      </code>
    </pre>
    <br/>
    Could also do this but less clear: <code><strong><u>var response = await callMe().catch((err) => &lbrace; console.error(err); &rbrace;);</u></strong></code><br/><br/>
    You can also do: <code><strong><u>let response = await fetch(url); </u></strong></code> (in async function, try in browser's console, Calling fetch () returns a promise)<br/><br/>
    If we call a function with await that just waits and then returns something, the wait will not wait (see explanation at top of section):<br/><br/>
    <pre>
      <code>
        function callMe()&lbrace;
        &nbsp;setTimeout(() => &lbrace;
        &nbsp;&nbsp;  return 9;
        &nbsp;  &rbrace;, 3000);  
        &rbrace;
      </code>
    </pre>
    











    </div>    
</div>
    